services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"

  api-gateway:
    image: kong:3.9
    environment:
      KONG_DATABASE: 'off'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002'
      KONG_DECLARATIVE_CONFIG: '/kong/config.yaml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - './docker/kong/config.yaml:/kong/config.yaml'
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8443:8443"
      - "8444:8444"

volumes:
  rabbitmq_data: